# Generated by Django 3.0.4 on 2020-11-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tikr', models.CharField(max_length=64)),
                ('buy', models.FloatField()),
                ('sl', models.FloatField()),
                ('qty', models.IntegerField()),
                ('t', models.FloatField()),
            ],
        ),
    ]
