# Generated by Django 3.0.4 on 2020-11-22 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector_analysis', '0002_ltp_tikrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdings',
            name='entrydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
