# Generated by Django 3.0.4 on 2020-11-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector_analysis', '0003_holdings_entrydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltp_tikrs',
            name='id',
        ),
        migrations.AlterField(
            model_name='ltp_tikrs',
            name='ltp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ltp_tikrs',
            name='tikr',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
