# Generated by Django 3.0.4 on 2020-11-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector_analysis', '0005_auto_20201125_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdings',
            name='sell_status',
            field=models.BooleanField(default=False),
        ),
    ]
