# Generated by Django 3.0.4 on 2020-11-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector_analysis', '0006_holdings_sell_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='exitdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
